[package]
name = "aoc2020"
version = "0.1.0"
authors = ["tgaede"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
regex = "1.4.2"
lazy_static = "1.4.0"
